# domain_anchors.py

DOMAIN_ANCHOR_QUERIES = {
    'donation': [
        "How to donate?",
        "How can I donate online?",
        "Please give me bank account details where I can donate?",
        "Do you guys have easy paisa?",
        "Do you guys have Jazz Cash?",
        "Can you collect donations from my home?",
        "Do you guys accept cash or cheque and what is the process?",
        "How can I pay in person?",
        "Does alkhidmat have any building where i can donate in person?",
        "Where do we get our donation receipts from?",
        "What is the link to donate?",
        "What are some programs that i donate to?",
        "Can i donate zakat and how?",
        "I am an overseas Pakistani, how can I donate?",
        "Which bank account should I donate to if I want to donate to Bano Qabil?",
        "I am from Europe, how can I donate?",
        "I am from America, how can I donate?",
        "How can I donate to Ghaza?",
        "I want to donate to education, how can I do that?",
        "Where are your buildings in Pakistan?",
        "What are some causes of donation that I can donate to?",
        "How can I make an online donation to Alkhidmat Foundation?",
        "Can I give zakat or sadaqah through debit card or mobile wallets?",
        "How do I donate for Gaza or Palestine emergency appeals?",
        "Is Alkhidmat Foundation tax exempted in Pakistan?",
        "Where can I donate in person or arrange a cash pick-up?",
        "What donation causes are currently available on Alkhidmat Foundation's website?",
    ],
    
    'healthcare': [
        "What are Alkhidmat's healthcare services?",
        "Which laboratory services do you provide?",
        "What are laboratories near my area?",
        "What is the ambulance number?",
        "What are the names of alkhidmat hospitals and where are they situated?",
        "What are alkhidmat hospitals near my area?",
        "What facilities can I get from alkhidmat's hospitals for free?",
        "How many Alkhidmat pharmacies are there?",
        "Can I get treatment at an Alkhidmat hospital?",
        "Do you offer diagnostic or laboratory services?",
        "Is blood available at your blood banks?",
        "Do you arrange free medical camps?",
        "Can thalassemia patients receive regular support?",
        "Do you provide dialysis treatment for patients?",
        "Is mother and child healthcare available?",
        "Do you conduct eye camps or eye surgeries?",
        "Can I get medicines from your pharmacies?",
        "Are primary healthcare centers available in rural areas?",
        "Do you provide delivery services for normal or C-section cases?",
        "Can patients receive one-month medical care support?",
        "Do you provide hygiene or safe delivery kits?",
        "How can I access Alkhidmat medical centers?",
        "Are ambulance services available 24/7?",
        "Do you run diagnostic centers or labs for patients?",
        "Can I get treatment through your medical camps?",
        "How many hospitals and healthcare facilities does Alkhidmat operate?",
        "Are Alkhidmat hospital services free or low-cost?",
        "Do your hospitals provide specialized medical treatments?",
        "How can a patient get admitted to an Alkhidmat hospital?",
        "How can I request an Alkhidmat ambulance in an emergency?",
        "Are Alkhidmat ambulances equipped with medical staff?",
        "Do your ambulance services operate day and night?",
        "Can I buy medicines from Alkhidmat pharmacies?",
        "Are medicines available at discounted prices at your pharmacies?",
        "Do Alkhidmat pharmacies provide diagnostic services as well?",
        "Do you set up medical camps in disaster-affected areas?",
        "What medical services are provided at Alkhidmat medical camps?",
        "Can patients receive treatment through field hospitals during emergencies?",
        "How can patients access blood from Alkhidmat blood banks?",
    ],
    
    'general': [
        "What services do you offer?",
        "How can I contact support?",
        "Tell me about your organization?",
        "What are alkhidmat's Office timings?",
        "Where are you located? your offices?",
        "What is Alkhidmat Foundation?",
        "Who founded Alkhidmat and when?",
        "Your mission and vision and what are your goals",
        "How many branches do you have?",
        "are there any Career opportunities available?",
        "Can you guide me through Volunteer registration process",
        "Give me Annual report information",
        "What are your Social media accounts",
        "What is your Email address for queries",
        "What is your Phone number for helpline",
        "Tell me your NGO registration details",
        "What is the history of the organization",
        "What are your Awards and recognition",
        "Are there any Partnership opportunities",
        "Give me Transparency reports",
        "What is your Head office address",
        "Tell me your Regional offices list",
        "Who are alkhidmat's Board of directors",
        "Give me alkhidmat's Chairman information",
        "what are alkhidmat's Latest news and updates",
    ]
}